const strings = {
	en: {
		statsTitle: 'Statistics',
		statsQuantity: 'Quizzes quantity:',
		statsUsers: 'New users of the month:',
		DeleteBtn: 'Delete',
		editBtn: 'Edit',
		BlockUserBtn: 'Block User',
		ActivateUserBtn: 'Activate User',
		stats: 'Statistics',
		category: 'Categories',
		user: 'Users',
		language: 'EN',
		logout: 'Log out',
		search: 'Search...',
		searchBtn: 'Search',
		addCat: 'Add Categories',
		addBtn: 'Add',
		validations: 'Validations',
		loading: 'Loading...',
		validationsTitle: 'User validations',
		validationsNoValidations: 'There are currently no users to validate.',
		validationReason: 'Reason to validate:',
		validationAccept: 'Accept',
		validationReject: 'Reject',
		cancel: 'Cancel',
		youSure: 'Are you sure?',
		cantUndo: "You can't undo this action afterwards.",
		quizDeleted: 'The quiz was deleted',
		userHas: 'The user has been',
		blocked: 'blocked',
		unblocked: 'unblocked',
		validationDeclined: 'The validation request has been declined',
		validationAccepted: 'The user has been validated',
		categoryDeleted: 'The category was deleted',
		categoryUpdated: 'Category updated',
		categoryCreated: 'Category created',
		promoteAdminBtn: 'Promote to Admin',
		demoteUserBtn: 'Demote to User',
		demote: 'demote',
		promote: 'promote',
		errorRole: 'Invalid credentials. Try again',
		errorRequiredEmail: 'Email is required',
		errorRequiredPassword: 'Password is required',
		errorInvalidMail: 'Invalid email',
	},

	es: {
		statsTitle: 'Estadísticas',
		statsQuantity: 'Cantidad de quizzes:',
		statsUsers: 'Nuevos usuarios del mes:',
		DeleteBtn: 'Eliminar',
		editBtn: 'Editar',
		BlockUserBtn: 'Bloquear Usuario',
		ActivateUserBtn: 'Activar Usuario',
		stats: 'Estadísticas',
		category: 'Categorías',
		user: 'Usuarios',
		language: 'ES',
		logout: 'Cerrar sesión',
		search: 'Buscar...',
		searchBtn: 'Buscar',
		addCat: 'Agregar Categorías',
		addBtn: 'Agregar',
		validations: 'Validaciones',
		loading: 'Cargando...',
		validationsTitle: 'Validaciones de usuarios',
		validationsNoValidations: 'No hay usuarios para validar actualmente.',
		validationReason: 'Razón de validación:',
		validationAccept: 'Aceptar',
		validationReject: 'Rechazar',
		cancel: 'Cancelar',
		youSure: 'Estás seguro?',
		cantUndo: 'No puedes deshacer esta acción',
		quizDeleted: 'El quiz ha sido eliminado',
		userHas: 'El usuario ha sido',
		blocked: 'bloqueado',
		unblocked: 'desbloqueado',
		validationDeclined: 'El pedido de validación ha sido rechazado',
		validationAccepted: 'El usuario ha sido validado',
		categoryDeleted: 'La categoría fue eliminada',
		categoryUpdated: 'Categoría actualizada',
		categoryCreated: 'Categoría creada',
		promoteAdminBtn: 'Promover a Admin',
		demoteUserBtn: 'Degradar a Usuario',
		demote: 'degradado',
		promote: 'promovido',
		errorRole: 'Credenciales invalidas. Intentalo nuevamente',
		errorRequiredEmail: 'El email es requerido',
		errorRequiredPassword: 'La contraseña es requerida',
		errorInvalidMail: 'E-mail invalido',
	},
};

export default strings;
