const strings = {
	en: {
		statsTitle: 'Statistics',
		statsQuantity: 'Quizzes quantity:',
		statsUsers: 'New users of the month:',
		DeleteBtn: 'Delete',
		editBtn: 'Edit',
		BlockUserBtn: 'Block User',
		ActivateUserBtn: 'Activate User',
		stats: 'Statistics',
		category: 'Categories',
		user: 'Users',
		language: 'Language',
		logout: 'Log out',
		search: 'Search...',
		searchBtn: 'Search',
		addCat: 'Add Categories',
		addBtn: 'Add',
		validations: 'Validations',
		loading: 'Loading...',
		validationsTitle: 'User validations',
		validationsNoValidations: 'There are currently no users to validate.',
		validationReason: 'Reason to validate:',
		validationAccept: 'Accept',
		validationReject: 'Reject',
		cancel: 'Cancel',
		youSure: 'Are you sure?',
		cantUndo: "You can't undo this action afterwards.",
	},

	es: {
		statsTitle: 'Estadísticas',
		statsQuantity: 'Cantidad de quizzes:',
		statsUsers: 'Nuevos usuarios del mes:',
		DeleteBtn: 'Eliminar',
		editBtn: 'Editar',
		BlockUserBtn: 'Bloquear Usuario',
		ActivateUserBtn: 'Activar Usuario',
		stats: 'Estadísticas',
		category: 'Categorías',
		user: 'Usuarios',
		language: 'Idioma',
		logout: 'Cerrar sesión',
		search: 'Buscar...',
		searchBtn: 'Buscar',
		addCat: 'Agregar Categorías',
		addBtn: 'Agregar',
		validations: 'Validaciones',
		loading: 'Cargando...',
		validationsTitle: 'Validaciones de usuarios',
		validationsNoValidations: 'No hay usuarios para validar actualmente.',
		validationReason: 'Razón de validación:',
		validationAccept: 'Aceptar',
		validationReject: 'Rechazar',
		cancel: 'Cancelar',
		youSure: 'Estás seguro?',
		cantUndo: 'No puedes deshacer esta acción',
	},
};

export default strings;
