const strings = {
	en: {
		statsTitle: 'Statistics',
		statsQuantity: 'Quizzes quantity:',
		statsUsers: 'New users of the month:',
		DeleteBtn: 'Delete',
		editBtn: 'Edit',
		BlockUserBtn: 'Block User',
		ActivateUserBtn: 'Activate User',
		stats: 'Statistics',
		category: 'Categories',
		user: 'Users',
		language: 'Language',
		logout: 'Log out',
		search: 'Search...',
		searchBtn: 'Search',
		addCat: 'Add Categories',
		addBtn: 'Add',
	},

	es: {
		statsTitle: 'Estadísticas',
		statsQuantity: 'Cantidad de quizzes:',
		statsUsers: 'Nuevos usuarios del mes:',
		DeleteBtn: 'Eliminar',
		editBtn: 'Editar',
		BlockUserBtn: 'Bloquear Usuario',
		ActivateUserBtn: 'Activar Usuario',
		stats: 'Estadísticas',
		category: 'Categorías',
		user: 'Usuarios',
		language: 'Idioma',
		logout: 'Cerrar sesión',
		search: 'Buscar...',
		searchBtn: 'Buscar',
		addCat: 'Agregar Categorías',
		addBtn: 'Agregar',
	},
};

export default strings;
